### ISSUE TITLE
Premature return

### ISSUE THREAD

**Issue by kevincolten** [pbullion/tdmpffl-with-database#1]
[You're returning after the first loop](https://github.com/pbullion/tdmpffl-with-database/blob/master/tdmpfflClass.py#L69)

**Comment by kevincolten** [comment]
@pbullion

**Comment by pbullion** [comment]
@kevincolten tried taking that out but it breaks, messing around with it any number works and also just taking out the =0, still just spits out the first entry. it has to be in my database class somewhere I'm thinking

**Comment by kevincolten** [comment]
@pbullion just updated the issue, it's actually just an indention error

**Comment by pbullion** [comment]
@kevincolten so stupid hahahah awesome thanks man
